// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fuxifuchs/backintime/src/services"

func sortable() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_sortable_2c1d`,
		Function: `function __templ_sortable_2c1d(){htmx.onLoad(function(content) {
    console.log('initting sortable', content)
    var sortables = document.querySelectorAll(".sortable");
    console.log(sortables)
    for (var i = 0; i < sortables.length; i++) {
      var sortable = sortables[i];
      var sortableInstance = new Sortable(sortable, {
          animation: 150,

          // Make the ` + "`" + `.htmx-indicator` + "`" + ` unsortable
          filter: ".htmx-indicator",
          onMove: function (evt) {
            return evt.related.className.indexOf('htmx-indicator') === -1;
          },

          // Disable sorting on the ` + "`" + `end` + "`" + ` event
     });

      // Re-enable sorting on the ` + "`" + `htmx:afterSwap` + "`" + ` event
      sortable.addEventListener("htmx:afterSwap", function() {
        sortableInstance.option("disabled", false);
      });
    }
  })}`,
		Call:       templ.SafeScript(`__templ_sortable_2c1d`),
		CallInline: templ.SafeScriptInline(`__templ_sortable_2c1d`),
	}
}

func handleAddCard(playlistUri string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_handleAddCard_7136`,
		Function: `function __templ_handleAddCard_7136(playlistUri){const token = localStorage.getItem("backInTime-token")
    const addButton = document.querySelector(".add-card-button")
    addButton.addEventListener("click", () => {
      addButton.disabled = true
      htmx.ajax('GET', "/user/play/newCard/"+playlistUri, { 
        target: ".card-wrapper", 
        swap: "beforeend",
        headers: { 
          Authorization: "Bearer "+token
        }
      })
    })}`,
		Call:       templ.SafeScript(`__templ_handleAddCard_7136`, playlistUri),
		CallInline: templ.SafeScriptInline(`__templ_handleAddCard_7136`, playlistUri),
	}
}

func Game(playlistUri string, gameEntry services.GameEntry) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"flex gap-8\"><div class=\"card-wrapper flex gap-8 sortable\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Card(playlistUri).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div style=\"box-shadow:8px 8px black\" class=\"border-4 border-dashed border-black p-3 flex\"><button disabled class=\"add-card-button text-3xl p-12 hover:bg-black hover:text-white rounded\" type=\"button\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `+ add Card`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SpotifyPlayer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = sortable().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = handleAddCard(playlistUri).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
